import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { dirname as win32Dirname } from "node:path/win32";
import {
  escapeSystemdExecPath,
  resolveServicePlatform,
  type ServicePlatform,
  xmlEscape,
} from "../config/service-definitions";
import {
  defaultRunCommand,
  queryWindowsTask,
  registerWindowsTask,
  restartWindowsTask,
  type RunCommand,
} from "../config/service-manager";

export const HERDR_SERVICE_MARKER = "Generated by roamgate herdr setup.";
export const HERDR_SERVICE_LABEL = "dev.roamgate.herdr";

export interface HerdrServicePaths {
  definition: string;
  taskName?: string;
  stdoutLog?: string;
  stderrLog?: string;
}

export interface HerdrServiceDeps {
  platform?: ServicePlatform;
  homeDir?: string;
  appDataDir?: string;
  uid?: number;
  runCommand?: RunCommand;
}

export function resolveHerdrServicePaths(
  platform: ServicePlatform,
  homeDir: string,
  appDataDir?: string,
): HerdrServicePaths {
  if (platform === "windows-task") {
    const base = join(
      appDataDir ?? join(homeDir, "AppData", "Roaming"),
      "roamgate",
    );
    const userKey = createHash("sha256")
      .update(base.toLowerCase())
      .digest("hex")
      .slice(0, 16);
    return {
      definition: join(base, "herdr-task.ps1"),
      taskName: `${HERDR_SERVICE_LABEL}-${userKey}`,
    };
  }
  if (platform === "systemd") {
    return {
      definition: join(
        homeDir,
        ".config",
        "systemd",
        "user",
        "roamgate-herdr.service",
      ),
    };
  }
  return {
    definition: join(
      homeDir,
      "Library",
      "LaunchAgents",
      `${HERDR_SERVICE_LABEL}.plist`,
    ),
    stdoutLog: join(homeDir, "Library", "Logs", "roamgate-herdr.stdout.log"),
    stderrLog: join(homeDir, "Library", "Logs", "roamgate-herdr.stderr.log"),
  };
}

export function renderHerdrSystemdService(binaryPath: string): string {
  return `# ${HERDR_SERVICE_MARKER}
[Unit]
Description=Herdr server (managed by Roamgate)
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=${escapeSystemdExecPath(binaryPath)} server
Restart=always
RestartSec=2
TimeoutStopSec=15

[Install]
WantedBy=default.target
`;
}

export function renderHerdrLaunchdService(
  binaryPath: string,
  paths: HerdrServicePaths,
): string {
  const programArguments = [binaryPath, "server"]
    .map((argument) => `    <string>${xmlEscape(argument)}</string>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${HERDR_SERVICE_MARKER} -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${HERDR_SERVICE_LABEL}</string>

  <key>ProgramArguments</key>
  <array>
${programArguments}
  </array>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>2</integer>
  <key>ProcessType</key>
  <string>Background</string>

  <key>StandardOutPath</key>
  <string>${xmlEscape(paths.stdoutLog ?? "")}</string>
  <key>StandardErrorPath</key>
  <string>${xmlEscape(paths.stderrLog ?? "")}</string>
</dict>
</plist>
`;
}

function powershellSingleQuotedString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function renderHerdrWindowsTask(
  binaryPath: string,
  paths: HerdrServicePaths,
): string {
  if (!paths.taskName) throw new Error("Windows service task name is missing");
  const taskName = powershellSingleQuotedString(paths.taskName);
  const executable = powershellSingleQuotedString(binaryPath);
  const argument = powershellSingleQuotedString("server");
  const workingDirectory = powershellSingleQuotedString(
    win32Dirname(binaryPath),
  );

  return `\uFEFF# ${HERDR_SERVICE_MARKER}
$ErrorActionPreference = "Stop"
$taskName = ${taskName}
$user = [Security.Principal.WindowsIdentity]::GetCurrent().Name
$action = New-ScheduledTaskAction -Execute ${executable} -Argument ${argument} -WorkingDirectory ${workingDirectory}
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $user
$principal = New-ScheduledTaskPrincipal -UserId $user -LogonType Interactive -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1)
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null
`;
}

function assertHerdrDefinitionWritable(path: string) {
  if (
    existsSync(path) &&
    !readFileSync(path, "utf8").includes(HERDR_SERVICE_MARKER)
  ) {
    throw new Error(
      `${path} was not generated by roamgate; remove it yourself before rerunning herdr setup`,
    );
  }
}

function writeHerdrDefinition(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true });
  const temporaryPath = `${path}.tmp-${process.pid}`;
  try {
    writeFileSync(temporaryPath, content, { mode: 0o644 });
    renameSync(temporaryPath, path);
  } finally {
    rmSync(temporaryPath, { force: true });
  }
}

function resolveDeps(deps: HerdrServiceDeps) {
  const platform = deps.platform ?? resolveServicePlatform(process.platform);
  return {
    platform,
    homeDir: deps.homeDir ?? homedir(),
    appDataDir: deps.appDataDir ?? process.env.APPDATA,
    uid: deps.uid ?? process.getuid?.(),
    runCommand: deps.runCommand ?? defaultRunCommand,
  };
}

function assertRunSucceeded(code: number, operation: string) {
  if (code !== 0) {
    throw new Error(`${operation} failed (exit ${code})`);
  }
}

/**
 * Install (or replace) the user service running `herdr server` and start it.
 * The unit is regenerated on every call so a changed binary path takes effect.
 */
export function installHerdrService(
  binaryPath: string,
  deps: HerdrServiceDeps = {},
): HerdrServicePaths {
  const { platform, homeDir, appDataDir, uid, runCommand } = resolveDeps(deps);
  const paths = resolveHerdrServicePaths(platform, homeDir, appDataDir);
  assertHerdrDefinitionWritable(paths.definition);
  if (paths.stdoutLog) mkdirSync(dirname(paths.stdoutLog), { recursive: true });

  if (platform === "systemd") {
    writeHerdrDefinition(
      paths.definition,
      renderHerdrSystemdService(binaryPath),
    );
    assertRunSucceeded(
      runCommand(["systemctl", "--user", "daemon-reload"]),
      "systemd daemon-reload",
    );
    assertRunSucceeded(
      runCommand(["systemctl", "--user", "enable", "roamgate-herdr.service"]),
      "systemd service enable",
    );
    // Explicit restart: `enable` does not restart an already-active service.
    assertRunSucceeded(
      runCommand(["systemctl", "--user", "restart", "roamgate-herdr.service"]),
      "systemd service start",
    );
    return paths;
  }

  if (platform === "launchd") {
    if (uid === undefined) {
      throw new Error("cannot determine the current user id for launchd");
    }
    writeHerdrDefinition(
      paths.definition,
      renderHerdrLaunchdService(binaryPath, paths),
    );
    const domain = `gui/${uid}`;
    const service = `${domain}/${HERDR_SERVICE_LABEL}`;
    if (runCommand(["launchctl", "print", service], { quiet: true }) === 0) {
      assertRunSucceeded(
        runCommand(["launchctl", "bootout", service]),
        "launchd service replacement",
      );
    }
    assertRunSucceeded(
      runCommand(["launchctl", "bootstrap", domain, paths.definition]),
      "launchd service start",
    );
    return paths;
  }

  writeHerdrDefinition(
    paths.definition,
    renderHerdrWindowsTask(binaryPath, paths),
  );
  assertRunSucceeded(
    registerWindowsTask(paths.definition, runCommand),
    "scheduled task registration",
  );
  assertRunSucceeded(
    restartWindowsTask(paths.taskName ?? "", runCommand),
    "scheduled task start",
  );
  return paths;
}

export function herdrServiceStatus(deps: HerdrServiceDeps = {}): {
  installed: boolean;
  active: boolean;
} {
  const { platform, homeDir, appDataDir, uid, runCommand } = resolveDeps(deps);
  const paths = resolveHerdrServicePaths(platform, homeDir, appDataDir);
  const installed = existsSync(paths.definition);
  if (platform === "systemd") {
    return {
      installed,
      active:
        runCommand(
          [
            "systemctl",
            "--user",
            "is-active",
            "--quiet",
            "roamgate-herdr.service",
          ],
          { quiet: true },
        ) === 0,
    };
  }
  if (platform === "launchd") {
    if (uid === undefined) return { installed, active: false };
    return {
      installed,
      active:
        runCommand(
          ["launchctl", "print", `gui/${uid}/${HERDR_SERVICE_LABEL}`],
          { quiet: true },
        ) === 0,
    };
  }
  if (!paths.taskName) return { installed, active: false };
  const query = queryWindowsTask(paths.taskName, runCommand);
  return { installed, active: query.status === "exists" && query.active };
}
