import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import {
  DEFAULT_SERVICE_ENV_FILE,
  escapeSystemdExecPath,
  GENERATED_MARKER,
  renderLaunchdService,
  renderSystemdService,
  renderWindowsTaskDefinition,
  resolveServicePaths,
  resolveLegacyServicePaths,
  resolveServicePlatform,
  SERVICE_LABEL,
  type ServicePlatform,
  type ServicePaths,
} from "./service-definitions";
import {
  assertSafeDataPath,
  migrateDataFile,
  publishDataFile,
} from "./data-paths";
import { roamgateEnv } from "./environment";
import { loadOrCreateAuthToken } from "./auth-token";
import {
  browserUrlFor,
  getLanIPs,
  isAnyHost,
  withLoginToken,
} from "./server-config";

type ServiceAction = "install" | "uninstall" | "status" | "restart" | "reload";

export const SERVICE_COMMAND_CONTINUE = Symbol("service-command-continue");

interface ServiceRuntime {
  platform: string;
  homeDir: string;
  appDataDir?: string;
  execPath: string;
  argv: string[];
  uid?: number;
}

export type RunCommand = (
  argv: string[],
  options?: { quiet?: boolean },
) => number;

interface ServiceCommandDependencies {
  runtime?: ServiceRuntime;
  runCommand?: RunCommand;
  getLanIPs?: () => string[];
  log?: (message: string) => void;
  error?: (message: string) => void;
}

interface ParsedServiceCommand {
  action: ServiceAction | "help" | "run";
  force: boolean;
  configPath?: string;
}

function parseServiceCommand(args: string[]): ParsedServiceCommand | null {
  if (args[0] !== "service") return null;
  const tail = args.slice(1);
  if (
    tail.length === 0 ||
    tail[0] === "help" ||
    tail.includes("--help") ||
    tail.includes("-h")
  ) {
    return { action: "help", force: false };
  }

  const action = tail[0];
  if (action === "run") {
    if (tail.length !== 2 || !tail[1]) {
      throw new Error("internal service run requires one environment file");
    }
    return { action: "run", force: false, configPath: tail[1] };
  }
  if (
    !["install", "uninstall", "status", "restart", "reload"].includes(action)
  ) {
    throw new Error(`unknown service action: ${action}`);
  }
  const options = tail.slice(1);
  const unknown = options.filter((option) => option !== "--force");
  if (unknown.length > 0) {
    throw new Error(`unknown service option: ${unknown[0]}`);
  }
  if (options.includes("--force") && action !== "install") {
    throw new Error("--force is only valid with `service install`");
  }
  return {
    action: action as ServiceAction,
    force: options.includes("--force"),
  };
}

function serviceHelp(): string {
  return `Manage Roamgate as a user service.

Usage:
  roamgate service install [--force]
  roamgate service status
  roamgate service restart
  roamgate service reload
  roamgate service uninstall

Linux uses a systemd user service. macOS uses a launchd LaunchAgent.
Windows uses a per-user Task Scheduler task that starts at login.
New services listen on 0.0.0.0 and use a generated login token by default.
Install prints tokenized login URLs, preserves the platform-specific
roamgate.env file, and starts the service.
Reload re-reads the service definition and restarts the process.
Use --force only to replace an existing service definition not generated by
roamgate. Uninstall preserves the environment file.
`;
}

export function defaultRunCommand(
  argv: string[],
  options: { quiet?: boolean } = {},
): number {
  const result = Bun.spawnSync(argv, {
    stdin: "inherit",
    stdout: options.quiet ? "ignore" : "inherit",
    stderr: options.quiet ? "ignore" : "inherit",
  });
  return result.exitCode ?? 1;
}

function ensureStandaloneBinary(runtime: ServiceRuntime): string {
  const invoked = runtime.argv[1] ?? "";
  const executable = basename(runtime.execPath).toLowerCase();
  if (
    executable === "bun" ||
    executable === "bun.exe" ||
    invoked.endsWith("src/index.ts")
  ) {
    throw new Error("service install requires the standalone roamgate binary");
  }
  return resolve(runtime.execPath);
}

const LEGACY_GENERATED_MARKER = "Generated by herdr-gui service install.";
const WINDOWS_TASK_NOT_FOUND_EXIT_CODE = 3;
const WINDOWS_TASK_INACTIVE_EXIT_CODE = 4;
// launchctl print returns 113 (service not found), not a generic query failure.
const LAUNCHD_SERVICE_NOT_FOUND_EXIT_CODE = 113;

type WindowsTaskQuery =
  | { status: "exists"; active: boolean }
  | { status: "missing" }
  | { status: "error"; code: number };

function windowsTaskName(paths: { taskName?: string }): string {
  if (!paths.taskName) throw new Error("Windows service task name is missing");
  return paths.taskName;
}

function powershellLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function queryWindowsTask(
  taskName: string,
  runCommand: RunCommand,
): WindowsTaskQuery {
  const task = powershellLiteral(taskName);
  const script = `try { $taskInfo = Get-ScheduledTask -TaskName ${task} -ErrorAction Stop; if ($taskInfo.State -eq 'Running') { exit 0 }; exit ${WINDOWS_TASK_INACTIVE_EXIT_CODE} } catch { if ($_.FullyQualifiedErrorId -like 'CmdletizationQuery_NotFound_TaskName*') { exit ${WINDOWS_TASK_NOT_FOUND_EXIT_CODE} }; Write-Error $_; exit 1 }`;
  const code = runCommand([
    "powershell.exe",
    "-NoProfile",
    "-NonInteractive",
    "-Command",
    script,
  ]);
  if (code === 0 || code === WINDOWS_TASK_INACTIVE_EXIT_CODE) {
    return { status: "exists", active: code === 0 };
  }
  if (code === WINDOWS_TASK_NOT_FOUND_EXIT_CODE) {
    return { status: "missing" };
  }
  return { status: "error", code };
}

export function registerWindowsTask(
  definitionPath: string,
  runCommand: RunCommand,
): number {
  return runCommand([
    "powershell.exe",
    "-NoProfile",
    "-NonInteractive",
    "-ExecutionPolicy",
    "Bypass",
    "-File",
    definitionPath,
  ]);
}

function waitForWindowsTaskStop(
  taskName: string,
  runCommand: RunCommand,
): number {
  const task = powershellLiteral(taskName);
  const script = `$deadline = (Get-Date).AddSeconds(15); while ((Get-Date) -lt $deadline) { try { $taskInfo = Get-ScheduledTask -TaskName ${task} -ErrorAction Stop } catch { if ($_.FullyQualifiedErrorId -like 'CmdletizationQuery_NotFound_TaskName*') { exit 0 }; Write-Error $_; exit 1 }; if ($taskInfo.State -ne 'Running') { exit 0 }; Start-Sleep -Milliseconds 100 }; Write-Error 'scheduled task did not stop within 15 seconds'; exit 1`;
  return runCommand([
    "powershell.exe",
    "-NoProfile",
    "-NonInteractive",
    "-Command",
    script,
  ]);
}

export function restartWindowsTask(
  taskName: string,
  runCommand: RunCommand,
): number {
  runCommand(["schtasks.exe", "/End", "/TN", taskName], { quiet: true });
  const waitCode = waitForWindowsTaskStop(taskName, runCommand);
  if (waitCode !== 0) return waitCode;
  return runCommand(["schtasks.exe", "/Run", "/TN", taskName]);
}

function assertServiceDefinitionWritable(path: string, force: boolean) {
  if (existsSync(path)) {
    const existing = readFileSync(path, "utf8");
    if (!existing.includes(GENERATED_MARKER) && !force) {
      throw new Error(
        `${path} was not generated by roamgate; rerun with --force to replace it`,
      );
    }
  }
}

function commandContainsArgument(command: string, argument: string): boolean {
  let offset = 0;
  while (offset < command.length) {
    const index = command.indexOf(argument, offset);
    if (index < 0) return false;
    const before = index === 0 ? "" : command[index - 1];
    const afterIndex = index + argument.length;
    const after = afterIndex >= command.length ? "" : command[afterIndex];
    const hasStartBoundary = before === "" || /\s|["']/.test(before);
    const hasEndBoundary = after === "" || /\s|["']/.test(after);
    if (hasStartBoundary && hasEndBoundary) return true;
    offset = index + argument.length;
  }
  return false;
}

function preservedSystemdExecStart(
  definitionPath: string,
  binaryPath: string,
): string | undefined {
  if (!existsSync(definitionPath)) return undefined;
  const contents = readFileSync(definitionPath, "utf8");
  if (!contents.includes(GENERATED_MARKER)) return undefined;

  const commands = contents
    .split(/\r?\n/)
    .filter((line) => line.startsWith("ExecStart="))
    .map((line) => line.slice("ExecStart=".length).trim())
    .filter(Boolean);
  if (commands.length !== 1) return undefined;

  const command = commands[0];
  const directCommands = new Set([
    binaryPath,
    escapeSystemdExecPath(binaryPath),
    // Recognize the quoted form emitted by herdr-gui <= 0.2.20 so reinstall
    // migrates it instead of treating it as a custom wrapper command.
    `"${binaryPath
      .replaceAll("\\", "\\\\")
      .replaceAll('"', '\\"')
      .replaceAll("%", "%%")}"`,
  ]);
  if (directCommands.has(command)) return undefined;

  // Keep an intentional supervisor wrapper only when it still launches the
  // exact binary being installed. Stale or unrelated commands are replaced.
  return commandContainsArgument(command, binaryPath) ? command : undefined;
}

function writeServiceDefinition(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true });
  const temporaryPath = `${path}.tmp-${process.pid}`;
  try {
    writeFileSync(temporaryPath, content, { mode: 0o644 });
    renameSync(temporaryPath, path);
  } finally {
    rmSync(temporaryPath, { force: true });
  }
}

function ensureEnvironmentFile(path: string): boolean {
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  const created = !existsSync(path);
  if (created) publishDataFile(path, DEFAULT_SERVICE_ENV_FILE);
  chmodSync(path, 0o600);
  return created;
}

function decodeEnvironmentValue(rawValue: string): string {
  const quote = rawValue[0];
  return rawValue.length >= 2 &&
    (quote === "'" || quote === '"') &&
    rawValue.at(-1) === quote
    ? rawValue.slice(1, -1)
    : rawValue;
}

function readEnvironmentValue(
  contents: string,
  name: string,
): string | undefined {
  let value: string | undefined;
  for (const line of contents.split(/\r?\n/)) {
    const match = line.match(
      new RegExp(`^\\s*(?:export\\s+)?${name}\\s*=\\s*(.*?)\\s*$`),
    );
    if (!match) continue;
    value = decodeEnvironmentValue(match[1] ?? "");
  }
  return value;
}

function loadServiceEnvironmentFile(path: string) {
  const contents = readFileSync(path, "utf8");
  for (const [index, line] of contents.split(/\r?\n/).entries()) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const match = line.match(
      /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/,
    );
    if (!match) {
      throw new Error(`invalid environment entry at ${path}:${index + 1}`);
    }
    process.env[match[1]] = decodeEnvironmentValue(match[2] ?? "");
  }
}

interface ServiceAccess {
  host: string;
  port: number;
  token?: string;
  tokenPath?: string;
  usesFixedPassword: boolean;
}

function prepareServiceAccess(configPath: string): ServiceAccess {
  const contents = readFileSync(configPath, "utf8");
  const host = readEnvironmentValue(contents, "HOST") || "127.0.0.1";
  const configuredPort = readEnvironmentValue(contents, "PORT");
  const port = Number(configuredPort || 8787);
  if (!Number.isInteger(port) || port < 1 || port > 65_535) {
    throw new Error(`invalid PORT in ${configPath}: ${configuredPort}`);
  }

  const password =
    readEnvironmentValue(contents, "ROAMGATE_PASSWORD") ??
    readEnvironmentValue(contents, "HERDR_GUI_PASSWORD") ??
    "";
  const usesFixedPassword = password.length > 0;
  if (
    usesFixedPassword ||
    host === "127.0.0.1" ||
    host === "localhost" ||
    host === "::1"
  ) {
    return { host, port, usesFixedPassword };
  }

  const tokenPath = join(dirname(configPath), "auth-token");
  return {
    host,
    port,
    token: loadOrCreateAuthToken(tokenPath),
    tokenPath,
    usesFixedPassword,
  };
}

function printServiceAccess(
  access: ServiceAccess,
  resolveLanIPs: () => string[],
  log: (message: string) => void,
) {
  if (access.usesFixedPassword) {
    log("Authentication: fixed password from the service config");
    log(`Open: ${browserUrlFor(access.host, access.port)}`);
    return;
  }
  if (!access.token) {
    log(`Open: ${browserUrlFor(access.host, access.port)} (local access)`);
    return;
  }

  log(`Login token: ${access.token}`);
  log(`Token file: ${access.tokenPath}`);
  log(
    `Open: ${withLoginToken(
      browserUrlFor(access.host, access.port),
      access.token,
    )}`,
  );
  if (isAnyHost(access.host)) {
    for (const ip of resolveLanIPs()) {
      log(
        `LAN: ${withLoginToken(`http://${ip}:${access.port}`, access.token)}`,
      );
    }
  }
}

function serviceExists(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  paths: ServicePaths,
  runCommand: RunCommand,
  identity: "legacy" | "Roamgate",
): boolean {
  if (existsSync(paths.definition)) return true;
  if (platform === "windows-task") {
    const query = queryWindowsTask(windowsTaskName(paths), runCommand);
    if (query.status === "error")
      throw new Error(
        `cannot check ${identity} scheduled task (exit ${query.code}); no service changes made`,
      );
    return query.status === "exists";
  }
  if (platform === "systemd") {
    const code = runCommand(
      [
        "systemctl",
        "--user",
        "--no-pager",
        "status",
        basename(paths.definition),
      ],
      { quiet: true },
    );
    if (code === 0 || code === 3) return true;
    if (code !== 4)
      throw new Error(
        `cannot check ${identity} systemd service (exit ${code}); no service changes made`,
      );
    return false;
  }
  if (runtime.uid === undefined)
    throw new Error("cannot determine the current user id for launchd");
  if (
    runCommand(["launchctl", "print", `gui/${runtime.uid}`], {
      quiet: true,
    }) !== 0
  )
    throw new Error(
      "cannot check launchd user domain; no service changes made",
    );
  const code = runCommand(
    [
      "launchctl",
      "print",
      `gui/${runtime.uid}/${basename(paths.definition, ".plist")}`,
    ],
    { quiet: true },
  );
  if (code === 0) return true;
  if (code !== LAUNCHD_SERVICE_NOT_FOUND_EXIT_CODE)
    throw new Error(
      `cannot check ${identity} launchd service (exit ${code}); no service changes made`,
    );
  return false;
}

function assertNoLegacyService(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  runCommand: RunCommand,
): void {
  const legacy = resolveLegacyServicePaths(
    platform,
    runtime.homeDir,
    runtime.appDataDir,
  );
  if (serviceExists(platform, runtime, legacy, runCommand, "legacy")) {
    throw new Error(
      `legacy service detected (${legacy.definition}); stop and uninstall it using the previous binary's service uninstall before activating Roamgate. For custom definitions, explicitly disable and archive them yourself. Preserve the legacy config and token. See docs/DEPLOYMENT.md#transition-from-herdr-studio--herdr-gui. --force does not bypass this check.`,
    );
  }
}

function isPublishedLegacyDefinition(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  paths: ServicePaths,
): boolean {
  const binary = resolve(runtime.execPath);
  let expected =
    platform === "systemd"
      ? renderSystemdService(binary, paths.config)
      : platform === "windows-task"
        ? renderWindowsTaskDefinition(binary, paths)
        : renderLaunchdService(binary, {
            ...paths,
            stdoutLog: join(
              runtime.homeDir,
              "Library",
              "Logs",
              "herdr-gui.stdout.log",
            ),
            stderrLog: join(
              runtime.homeDir,
              "Library",
              "Logs",
              "herdr-gui.stderr.log",
            ),
          });
  // Reconstruct the published 0.7.0 template using this executable's path.
  // Customized scripts, labels, commands and other binaries require manual care.
  expected = expected.replace(GENERATED_MARKER, LEGACY_GENERATED_MARKER);
  if (platform === "launchd") {
    expected = expected
      .replace(
        "<string>dev.roamgate</string>",
        "<string>dev.herdr.herdr-gui</string>",
      )
      .replace(
        "<string>roamgate-service</string>",
        "<string>herdr-gui-service</string>",
      )
      .replace(
        "  <key>RunAtLoad</key>",
        `  <key>EnvironmentVariables</key>\n  <dict>\n    <key>HERDR_GUI_RESTART_SUPERVISOR</key>\n    <string>1</string>\n  </dict>\n\n  <key>RunAtLoad</key>`,
      );
  }
  return (
    readFileSync(paths.definition, "utf8").replaceAll("\r\n", "\n") === expected
  );
}

function managedServicePaths(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  runCommand: RunCommand,
  log: (message: string) => void,
): ServicePaths {
  const current = resolveServicePaths(
    platform,
    runtime.homeDir,
    runtime.appDataDir,
  );
  const legacy = resolveLegacyServicePaths(
    platform,
    runtime.homeDir,
    runtime.appDataDir,
  );
  assertSafeDataPath(legacy.definition);
  if (
    existsSync(legacy.definition) &&
    isPublishedLegacyDefinition(platform, runtime, legacy)
  ) {
    if (serviceExists(platform, runtime, current, runCommand, "Roamgate")) {
      throw new Error(
        "both Roamgate and legacy services exist; resolve the duplicate services with the previous binary or native service manager before continuing; no service changes made",
      );
    }
    log(
      `Managing legacy service: ${legacy.definition}; its name and configuration are preserved. Uninstall it before installing the new Roamgate service.`,
    );
    return legacy;
  }
  // Unmanaged or loaded-only legacy services require explicit owner intervention.
  assertNoLegacyService(platform, runtime, runCommand);
  return current;
}

function installService(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  force: boolean,
  runCommand: RunCommand,
  resolveLanIPs: () => string[],
  log: (message: string) => void,
): number {
  const binaryPath = ensureStandaloneBinary(runtime);
  if (platform === "launchd" && runtime.uid === undefined) {
    throw new Error("cannot determine the current user id for launchd");
  }
  const paths = resolveServicePaths(
    platform,
    runtime.homeDir,
    runtime.appDataDir,
  );
  if (platform === "windows-task") {
    const taskName = windowsTaskName(paths);
    const taskQuery = queryWindowsTask(taskName, runCommand);
    if (taskQuery.status === "error") return taskQuery.code;
    if (
      taskQuery.status === "exists" &&
      !existsSync(paths.definition) &&
      !force
    ) {
      throw new Error(
        `scheduled task ${taskName} already exists; rerun with --force to replace it`,
      );
    }
  }
  assertServiceDefinitionWritable(paths.definition, force);
  const legacy = resolveLegacyServicePaths(
    platform,
    runtime.homeDir,
    runtime.appDataDir,
  );
  migrateDataFile(paths.config, legacy.config);
  migrateDataFile(
    join(dirname(paths.config), "auth-token"),
    join(dirname(legacy.config), "auth-token"),
  );
  const environmentCreated = ensureEnvironmentFile(paths.config);
  const access = prepareServiceAccess(paths.config);
  if (paths.stdoutLog) mkdirSync(dirname(paths.stdoutLog), { recursive: true });
  const customSystemdExecStart =
    platform === "systemd"
      ? preservedSystemdExecStart(paths.definition, binaryPath)
      : undefined;
  const definition =
    platform === "systemd"
      ? renderSystemdService(binaryPath, paths.config, customSystemdExecStart)
      : platform === "launchd"
        ? renderLaunchdService(binaryPath, paths)
        : renderWindowsTaskDefinition(binaryPath, paths);
  writeServiceDefinition(paths.definition, definition);

  let code: number;
  if (platform === "systemd") {
    code = runCommand(["systemctl", "--user", "daemon-reload"]);
    if (code === 0) {
      code = runCommand(["systemctl", "--user", "enable", "roamgate.service"]);
    }
    if (code === 0) {
      // `enable --now` does not restart an already-active service after its
      // definition changes. An explicit restart makes reinstall deterministic.
      code = runCommand(["systemctl", "--user", "restart", "roamgate.service"]);
    }
  } else if (platform === "launchd") {
    const domain = `gui/${runtime.uid}`;
    const service = `${domain}/${SERVICE_LABEL}`;
    const loaded =
      runCommand(["launchctl", "print", service], { quiet: true }) === 0;
    if (loaded) {
      code = runCommand(["launchctl", "bootout", service]);
    } else {
      code = 0;
    }
    if (code === 0) {
      code = runCommand(["launchctl", "bootstrap", domain, paths.definition]);
    }
  } else {
    code = registerWindowsTask(paths.definition, runCommand);
    if (code === 0) {
      code = restartWindowsTask(windowsTaskName(paths), runCommand);
    }
  }

  if (code === 0) {
    log(`Installed ${platform} service: ${paths.definition}`);
    log(
      environmentCreated
        ? `Created service config: ${paths.config}`
        : `Preserved service config: ${paths.config}`,
    );
    if (customSystemdExecStart) {
      log(`Preserved custom ExecStart: ${customSystemdExecStart}`);
    }
    printServiceAccess(access, resolveLanIPs, log);
  }
  return code;
}

function uninstallService(
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  paths: ServicePaths,
  runCommand: RunCommand,
  log: (message: string) => void,
): number {
  const definitionExists = existsSync(paths.definition);
  if (!definitionExists && platform !== "windows-task") {
    log(`No managed ${platform} service found: ${paths.definition}`);
    log(`Preserved service config: ${paths.config}`);
    return 0;
  }
  if (
    definitionExists &&
    ![GENERATED_MARKER, LEGACY_GENERATED_MARKER].some((marker) =>
      readFileSync(paths.definition, "utf8").includes(marker),
    )
  ) {
    throw new Error(
      `${paths.definition} was not generated by roamgate and will not be removed`,
    );
  }
  if (platform === "systemd") {
    const stopCode = runCommand([
      "systemctl",
      "--user",
      "disable",
      "--now",
      basename(paths.definition),
    ]);
    if (stopCode !== 0) return stopCode;
    const backupPath = `${paths.definition}.uninstall-${process.pid}`;
    if (existsSync(backupPath))
      throw new Error(`service backup already exists: ${backupPath}`);
    renameSync(paths.definition, backupPath);
    try {
      const code = runCommand(["systemctl", "--user", "daemon-reload"]);
      if (code !== 0) return code;
      rmSync(backupPath);
    } finally {
      if (existsSync(backupPath)) renameSync(backupPath, paths.definition);
    }
  } else if (platform === "launchd") {
    if (runtime.uid === undefined) {
      throw new Error("cannot determine the current user id for launchd");
    }
    const service = `gui/${runtime.uid}/${basename(paths.definition, ".plist")}`;
    const queryCode = runCommand(["launchctl", "print", service], {
      quiet: true,
    });
    if (queryCode !== 0 && queryCode !== LAUNCHD_SERVICE_NOT_FOUND_EXIT_CODE)
      return queryCode;
    if (queryCode === 0) {
      const stopCode = runCommand(["launchctl", "bootout", service]);
      if (stopCode !== 0) return stopCode;
    }
    rmSync(paths.definition, { force: true });
  } else {
    const taskName = windowsTaskName(paths);
    const taskQuery = queryWindowsTask(taskName, runCommand);
    if (taskQuery.status === "error") return taskQuery.code;
    const taskExists = taskQuery.status === "exists";
    if (!definitionExists && !taskExists) {
      log(`No managed ${platform} service found: ${paths.definition}`);
      log(`Preserved service config: ${paths.config}`);
      return 0;
    }
    if (taskExists) {
      runCommand(["schtasks.exe", "/End", "/TN", taskName], {
        quiet: true,
      });
      const waitCode = waitForWindowsTaskStop(taskName, runCommand);
      if (waitCode !== 0) return waitCode;
      const deleteCode = runCommand([
        "schtasks.exe",
        "/Delete",
        "/TN",
        taskName,
        "/F",
      ]);
      if (deleteCode !== 0) {
        const afterDelete = queryWindowsTask(taskName, runCommand);
        if (afterDelete.status === "error") return afterDelete.code;
        if (afterDelete.status === "exists") return deleteCode;
      }
    }
    rmSync(paths.definition, { force: true });
  }
  log(`Removed ${platform} service: ${paths.definition}`);
  log(`Preserved service config: ${paths.config}`);
  return 0;
}

function runServiceAction(
  action: Exclude<ServiceAction, "install" | "uninstall">,
  platform: ServicePlatform,
  runtime: ServiceRuntime,
  paths: ServicePaths,
  runCommand: RunCommand,
): number {
  const serviceName = basename(paths.definition, ".plist");
  if (action === "reload") {
    if (!existsSync(paths.definition)) {
      throw new Error(
        `cannot reload missing ${platform} service: ${paths.definition}`,
      );
    }
    if (platform === "systemd") {
      const reloadCode = runCommand(["systemctl", "--user", "daemon-reload"]);
      if (reloadCode !== 0) return reloadCode;
      return runCommand(["systemctl", "--user", "restart", serviceName]);
    }
    if (platform === "windows-task") {
      const registerCode = registerWindowsTask(paths.definition, runCommand);
      return registerCode === 0
        ? restartWindowsTask(windowsTaskName(paths), runCommand)
        : registerCode;
    }
    if (runtime.uid === undefined) {
      throw new Error("cannot determine the current user id for launchd");
    }
    const domain = `gui/${runtime.uid}`;
    const service = `${domain}/${serviceName}`;
    const queryCode = runCommand(["launchctl", "print", service], {
      quiet: true,
    });
    if (queryCode !== 0 && queryCode !== LAUNCHD_SERVICE_NOT_FOUND_EXIT_CODE)
      return queryCode;
    if (queryCode === 0) {
      const bootoutCode = runCommand(["launchctl", "bootout", service]);
      if (bootoutCode !== 0) return bootoutCode;
    }
    return runCommand(["launchctl", "bootstrap", domain, paths.definition]);
  }
  if (platform === "systemd") {
    return runCommand(
      action === "status"
        ? ["systemctl", "--user", "--no-pager", "status", serviceName]
        : ["systemctl", "--user", "restart", serviceName],
    );
  }
  if (platform === "windows-task") {
    const taskName = windowsTaskName(paths);
    return action === "status"
      ? runCommand([
          "schtasks.exe",
          "/Query",
          "/TN",
          taskName,
          "/V",
          "/FO",
          "LIST",
        ])
      : restartWindowsTask(taskName, runCommand);
  }
  if (runtime.uid === undefined) {
    throw new Error("cannot determine the current user id for launchd");
  }
  const service = `gui/${runtime.uid}/${serviceName}`;
  return runCommand(
    action === "status"
      ? ["launchctl", "print", service]
      : ["launchctl", "kickstart", "-k", service],
  );
}

export function runServiceCommand(
  args: string[],
  dependencies: ServiceCommandDependencies = {},
): number | null | typeof SERVICE_COMMAND_CONTINUE {
  const log = dependencies.log ?? console.log;
  const error = dependencies.error ?? console.error;
  let command: ParsedServiceCommand | null;
  try {
    command = parseServiceCommand(args);
    if (!command) return null;
    if (command.action === "help") {
      log(serviceHelp());
      return 0;
    }
    if (command.action === "run") {
      loadServiceEnvironmentFile(command.configPath ?? "");
      if (roamgateEnv("RESTART_SUPERVISOR") === undefined) {
        process.env.ROAMGATE_RESTART_SUPERVISOR = "1";
      }
      return SERVICE_COMMAND_CONTINUE;
    }

    const runtime: ServiceRuntime = dependencies.runtime ?? {
      platform: process.platform,
      homeDir: homedir(),
      appDataDir: process.env.APPDATA,
      execPath: process.execPath,
      argv: process.argv,
      uid: process.getuid?.(),
    };
    const platform = resolveServicePlatform(runtime.platform);
    const runCommand = dependencies.runCommand ?? defaultRunCommand;
    if (command.action === "install") {
      assertNoLegacyService(platform, runtime, runCommand);
      return installService(
        platform,
        runtime,
        command.force,
        runCommand,
        dependencies.getLanIPs ?? getLanIPs,
        log,
      );
    }
    const paths = managedServicePaths(platform, runtime, runCommand, log);
    if (command.action === "uninstall") {
      return uninstallService(platform, runtime, paths, runCommand, log);
    }
    return runServiceAction(
      command.action,
      platform,
      runtime,
      paths,
      runCommand,
    );
  } catch (cause) {
    error(`roamgate service: ${(cause as Error).message}`);
    error("Run `roamgate service --help` for usage.");
    return 1;
  }
}
