#!/usr/bin/env bun
// Prepare a release PR by bumping the package.json and herdr-plugin.toml
// versions. Release notes are generated by GitHub from merged PRs, so this
// script only updates the working tree; it does not commit, merge, tag, or
// push anything.
//
// Usage:
//   bun scripts/prepare-release.ts <X.Y.Z | patch | minor | major>
//   bun scripts/prepare-release.ts 0.4.6
//   bun scripts/prepare-release.ts patch

import { execFileSync, spawnSync } from "node:child_process";
import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const PACKAGE_FILES = [
  "package.json",
  "web/package.json",
  "server/package.json",
];
const PLUGIN_MANIFEST_FILE = "herdr-plugin.toml";
const RELEASE_FILES = [...PACKAGE_FILES, PLUGIN_MANIFEST_FILE];

const SEMVER_RE = /^(\d+)\.(\d+)\.(\d+)$/;

export function parsePackageVersion(packageJsonText: string): string {
  const match = /^(\s*)"version": "([^"]+)"/m.exec(packageJsonText);
  if (!match) {
    throw new Error('package.json has no top-level "version" field');
  }
  return match[2];
}

export function replacePackageVersion(
  packageJsonText: string,
  expectedCurrent: string,
  next: string,
): string {
  const match = /^(\s*)"version": "([^"]+)"/m.exec(packageJsonText);
  if (!match || match.index === undefined) {
    throw new Error('package.json has no top-level "version" field');
  }
  if (match[2] !== expectedCurrent) {
    throw new Error(
      `package.json version is ${match[2]}, expected ${expectedCurrent}`,
    );
  }
  return `${packageJsonText.slice(0, match.index)}${match[1]}"version": "${next}"${packageJsonText.slice(
    match.index + match[0].length,
  )}`;
}

export function parseManifestVersion(manifestText: string): string {
  const match = /^(\s*)version = "([^"]+)"/m.exec(manifestText);
  if (!match) {
    throw new Error('herdr-plugin.toml has no top-level "version" field');
  }
  return match[2];
}

export function replaceManifestVersion(
  manifestText: string,
  expectedCurrent: string,
  next: string,
): string {
  const match = /^(\s*)version = "([^"]+)"/m.exec(manifestText);
  if (!match || match.index === undefined) {
    throw new Error('herdr-plugin.toml has no top-level "version" field');
  }
  if (match[2] !== expectedCurrent) {
    throw new Error(
      `herdr-plugin.toml version is ${match[2]}, expected ${expectedCurrent}`,
    );
  }
  return `${manifestText.slice(0, match.index)}${match[1]}version = "${next}"${manifestText.slice(
    match.index + match[0].length,
  )}`;
}

export function resolveNextVersion(current: string, input: string): string {
  const currentMatch = SEMVER_RE.exec(current);
  if (!currentMatch) {
    throw new Error(`Current version "${current}" is not in X.Y.Z form`);
  }
  const currentTuple = [
    Number(currentMatch[1]),
    Number(currentMatch[2]),
    Number(currentMatch[3]),
  ];
  if (input === "patch") {
    return `${currentTuple[0]}.${currentTuple[1]}.${currentTuple[2] + 1}`;
  }
  if (input === "minor") {
    return `${currentTuple[0]}.${currentTuple[1] + 1}.0`;
  }
  if (input === "major") {
    return `${currentTuple[0] + 1}.0.0`;
  }
  const nextMatch = SEMVER_RE.exec(input);
  if (!nextMatch) {
    throw new Error(`Version "${input}" must be X.Y.Z or patch|minor|major`);
  }
  const candidate = [
    Number(nextMatch[1]),
    Number(nextMatch[2]),
    Number(nextMatch[3]),
  ];
  for (let index = 0; index < 3; index += 1) {
    if (candidate[index] > currentTuple[index]) return input;
    if (candidate[index] < currentTuple[index]) break;
  }
  throw new Error(
    `Version ${input} must be greater than the current ${current}`,
  );
}

function git(...args: string[]): string {
  return execFileSync("git", args, { cwd: REPO_ROOT, encoding: "utf8" }).trim();
}

function gitTagExists(tag: string): boolean {
  const result = spawnSync(
    "git",
    ["rev-parse", "--verify", "--quiet", `refs/tags/${tag}`],
    { cwd: REPO_ROOT, encoding: "utf8" },
  );
  if (result.error) {
    throw new Error(
      `could not run git while inspecting tag ${tag}: ${result.error.message}`,
    );
  }
  if (result.status === 0) return true;
  if (result.status === 1) return false;
  throw new Error(result.stderr.trim() || `could not inspect tag ${tag}`);
}

function abort(message: string): never {
  console.error(`prepare-release: ${message}`);
  process.exit(1);
}

function main() {
  const input = process.argv[2];
  if (!input || input === "--help") {
    console.log(
      "Usage: bun scripts/prepare-release.ts <X.Y.Z | patch | minor | major>",
    );
    process.exit(input ? 0 : 1);
  }
  if (process.argv.length > 3) {
    abort("unexpected extra arguments");
  }

  const dirty = git("status", "--porcelain", "--", ...RELEASE_FILES);
  if (dirty) {
    abort(
      `release files have uncommitted changes, commit or stash them first:\n${dirty}`,
    );
  }

  const packageSources = PACKAGE_FILES.map((file) => {
    const path = join(REPO_ROOT, file);
    const text = readFileSync(path, "utf8");
    return { file, path, text, version: parsePackageVersion(text) };
  });
  const current = packageSources[0].version;
  const mismatchedPackage = packageSources.find(
    ({ version }) => version !== current,
  );
  if (mismatchedPackage) {
    abort(
      `${mismatchedPackage.file} version is ${mismatchedPackage.version}, expected ${current}`,
    );
  }
  const manifestPath = join(REPO_ROOT, PLUGIN_MANIFEST_FILE);
  const manifestText = readFileSync(manifestPath, "utf8");
  if (parseManifestVersion(manifestText) !== current) {
    abort(
      `${PLUGIN_MANIFEST_FILE} version is ${parseManifestVersion(manifestText)}, expected ${current}`,
    );
  }

  const version = resolveNextVersion(current, input);
  const tag = `v${version}`;
  if (gitTagExists(tag)) {
    abort(`tag ${tag} already exists; fetch tags before preparing a release`);
  }

  // Compute every output before writing anything so a validation failure
  // leaves the worktree untouched.
  const packageWrites = packageSources.map(({ path, text }) => ({
    path,
    text: replacePackageVersion(text, current, version),
  }));
  const manifestWrite = replaceManifestVersion(manifestText, current, version);
  for (const { path, text } of packageWrites) {
    writeFileSync(path, text);
  }
  writeFileSync(manifestPath, manifestWrite);

  console.log(
    `Prepared release ${version}. Review the changes and submit them as a release PR.`,
  );

  if (process.env.GITHUB_OUTPUT) {
    appendFileSync(
      process.env.GITHUB_OUTPUT,
      `version=${version}\ntag=${tag}\n`,
    );
  }
}

if (import.meta.main) {
  try {
    main();
  } catch (error) {
    abort(error instanceof Error ? error.message : String(error));
  }
}
