import { describe, expect, test } from "bun:test";
import {
  diffAutoCollapseInfo,
  LARGE_DIFF_CHANGED_LINES,
  LARGE_DIFF_FILE_BYTES,
  LARGE_DIFF_PATCH_BYTES,
} from "./diffAutoCollapse";
import type { GitDiffEntry, GitDiffFile } from "../types";

function entry(patch: Partial<GitDiffEntry> = {}): GitDiffEntry {
  return {
    path: "src/app.ts",
    kind: "unstaged",
    status: "modified",
    ...patch,
  };
}

function file(patch: Partial<GitDiffFile> = {}): GitDiffFile {
  return {
    workspace_id: "workspace",
    root: "/repo",
    path: "src/app.ts",
    kind: "unstaged",
    diff: "",
    truncated: false,
    ...patch,
  };
}

describe("diffAutoCollapseInfo", () => {
  test("collapses files marked generated by Git attributes", () => {
    expect(diffAutoCollapseInfo(entry({ generated: true }))).toEqual({
      reason: "generated",
      label: "generated file",
    });
  });

  test("collapses diffs at the large line threshold", () => {
    expect(
      diffAutoCollapseInfo(
        entry({ additions: LARGE_DIFF_CHANGED_LINES - 1, deletions: 1 }),
      ),
    ).toEqual({
      reason: "large",
      label: "1,000 changed lines",
    });
  });

  test("collapses byte-truncated diffs and leaves ordinary diffs open", () => {
    expect(diffAutoCollapseInfo(entry(), file({ truncated: true }))).toEqual({
      reason: "truncated",
      label: "large diff",
    });
    expect(
      diffAutoCollapseInfo(entry({ additions: 20, deletions: 10 }), file()),
    ).toBeNull();
  });

  test("skips large files and single-line patches before expensive rendering", () => {
    expect(diffAutoCollapseInfo(entry(), file({ deferred: true }))).toEqual({
      reason: "large",
      label: "large diff",
    });
    expect(
      diffAutoCollapseInfo(
        entry({ additions: 1, file_size: LARGE_DIFF_FILE_BYTES }),
      ),
    ).toEqual({ reason: "large", label: "large file" });
    expect(
      diffAutoCollapseInfo(
        entry({ additions: 1 }),
        file({ patch_size: LARGE_DIFF_PATCH_BYTES }),
      ),
    ).toEqual({ reason: "large", label: "large diff" });
    expect(
      diffAutoCollapseInfo(
        entry({ file_size: LARGE_DIFF_FILE_BYTES - 1 }),
        file({ patch_size: LARGE_DIFF_PATCH_BYTES - 1 }),
      ),
    ).toBeNull();
    // Working-tree size is a fingerprint, not the size of every compared blob.
    expect(
      diffAutoCollapseInfo(entry({ size: LARGE_DIFF_FILE_BYTES })),
    ).toBeNull();
  });
});
